server:
	port: ${PORT:0}$
spring:
	application:
		name: api-movie
	datasource:
		driverClassName: om.msql.cj.jdbc.Driver

		url: jdbc:h2:~/db_movies
		username: sa
	jpa:
		properties:
			hibernate:
				dialect: org.hibernate.dialect.H2Dialect
				show-sql: true
	h2:
		console:
		enable: true
		path: /h2-console

mensagem: bienvenido a api-movie
		
info:
	application:
		name: api-movie


eureka:
	instance:
		hostname: localhost
		instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
	client:
		registerWithEureka: true
		fetchRegistry: true
		serviceUrl:
			defaultZone: http://localhost:8761/eureka/
